all:
  vars:
    ansible_user: centos
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
prod:
  hosts:
    client:
       ansible_host: 3.80.95.225 # A remplacer par l'IP ou le DNS de votre machine cible
  vars:
    env: production
    ansible_password: centos
    red_color: "red"
    blue_color: "blue"
