all:
  vars:
    ansible_user: cloud_user
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
prod:
  hosts:
    client:
       ansible_host: 13.40.134.218 # A remplacer par l'IP ou le DNS de votre machine cible
  vars:
    env: production
    ansible_password: Aube5232@
    red_color: "red"
    blue_color: "blue"
